"""Added dates

Revision ID: 25e4b23d91c1
Revises: d0d9bdf0ffca
Create Date: 2021-07-14 14:26:18.256417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e4b23d91c1'
down_revision = 'd0d9bdf0ffca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'project_created_at')
    # ### end Alembic commands ###
