"""empty message

Revision ID: 4a74127d9043
Revises: 945a7ec0072b
Create Date: 2021-05-20 05:18:53.675495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a74127d9043'
down_revision = '945a7ec0072b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=64), nullable=True),
    sa.Column('project_desc', sa.String(length=120), nullable=True),
    sa.Column('num_members', sa.Integer(), nullable=True),
    sa.Column('num_tasks', sa.Integer(), nullable=True),
    sa.Column('project_last_changed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_project_name'), 'project', ['project_name'], unique=True)
    op.drop_column('user', 'profile_desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_desc', sa.VARCHAR(length=140), nullable=True))
    op.drop_index(op.f('ix_project_project_name'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
