"""Removed dumb column

Revision ID: 945a7ec0072b
Revises: 2529ee372057
Create Date: 2021-05-17 22:31:43.588684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945a7ec0072b'
down_revision = '2529ee372057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_desc', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
