"""Removed unqiue constraint

Revision ID: a4c1ff15b4da
Revises: 2a44f0ceff5f
Create Date: 2021-05-21 00:31:48.959432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c1ff15b4da'
down_revision = '2a44f0ceff5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_project_name', table_name='project')
    op.create_index(op.f('ix_project_project_name'), 'project', ['project_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_project_name'), table_name='project')
    op.create_index('ix_project_project_name', 'project', ['project_name'], unique=False)
    # ### end Alembic commands ###
